name: Pull Request Validation Pipeline

on:
  push:
    branches:
      - pr-pipeline
  pull_request:
    branches:
      - pr-pipeline
    types: [opened, synchronize, reopened]

jobs:
  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for Sonar relevance

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Step 3: Install dependencies for SonarQube (if any)
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 4: Run SonarQube Analysis
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Fail the job if SonarQube finds issues
    outputs:
      sonar-status: ${{ steps.sonar.outputs.sonar-status }}
    continue-on-error: false  # Fail the workflow if the analysis fails
