name: Build and Deploy PHP Application

on:
  push:
    branches:
      - pr-pipelinenew
  pull_request:
    branches:
      - pr-pipelinenew
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better Sonar relevance

      # Step 2: Run SonarQube Analysis
      - name: SonarQube Cloud Scan
        id: sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 3: Debug SonarQube Output
      - name: Debug SonarQube Quality Gate Status
        run: |
          echo "SonarQube Quality Gate Status: ${{ steps.sonar.outputs.sonar-quality-gate-status }}"

      # Step 4: Fail Workflow on SonarQube Quality Gate Failure
      - name: Fail Workflow on SonarQube Quality Gate Failure
        if: ${{ steps.sonar.outputs.sonar-quality-gate-status != 'PASSED' }}
        run: |
          echo "SonarQube Quality Gate failed."
          exit 1


      # Step 4: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Step 5: Run PHP Lint
      - name: Run PHP Lint
        run: |
          php -l index.php

      # Step 6: Run PHP Unit Tests (if any)
      - name: Run Tests
        run: |
          if [ -d tests ]; then
            ./vendor/bin/phpunit --configuration phpunit.xml
          else
            echo "No tests found, skipping."
          fi

      # Step 7: Install Composer Dependencies
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 8: Prepare files for deployment
      - name: Prepare files for deployment
        run: |
          mkdir -p ./publish
          rsync -av --progress . ./publish --exclude publish --exclude private_key.pem

      # Step 9: Create target directory on the remote server (GCP VM)
      - name: Create target directory on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/${{ secrets.GCP_USER }}/php-app/
            chmod 755 /home/${{ secrets.GCP_USER }}/php-app/

      # Step 10: Deploy application to GCP VM
      - name: Deploy to GCP VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./publish/*"
          target: "/home/${{ secrets.GCP_USER }}/php-app/"

      # Step 11: Start PHP Server
      - name: Start PHP Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/php-app/publish
            nohup php -S 0.0.0.0:8004 > php_server.log 2>&1

