name: PR SonarQube and Auto-Merge

on:
  pull_request:
    branches:
      - security-pipeline
    types: [opened, synchronize, reopened]

jobs:
  sonar_scan:
    name: Run SonarQube and Auto-Merge
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the entire history for SonarQube analysis

      # Step 2: Run SonarQube Scan
      - name: SonarQube Scan
        id: sonar_scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR context
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 3: Check SonarQube Quality Gate
      - name: Check SonarQube Quality Gate
        id: quality_gate
        run: |
          # Fetch the SonarQube quality gate status
          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ github.repository }}" | jq -r '.projectStatus.status')

          echo "SonarQube Quality Gate Status: $status"
          echo "::set-output name=status::$status"

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 4: Conditionally Merge PR if SonarQube Passed
      - name: Merge Pull Request
        if: steps.quality_gate.outputs.status == 'OK'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Fail the workflow if SonarQube fails
      - name: Fail Workflow
        if: steps.quality_gate.outputs.status != 'OK'
        run: |
          echo "SonarQube Quality Gate failed. Stopping PR merge."
          exit 1
